remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Java Backend Interview Guide
description: Curated Java, Spring Boot, Microservices, Kafka, Database, Production, and System Design interview preparation.
exclude:
- Gemfile
- Gemfile.lock
- vendor
- jekyll-server.out
- jekyll-server.err
